<?php
/**
 * DecorArt Core — Mini-CRM e Agenda/Planner.
 * Interface administrativa protegida pelo WordPress; sem rota pública ou REST.
 */
if (!defined('ABSPATH')) { exit; }

function da_crm_can() { return current_user_can('edit_posts'); }
function da_admin_url($page, $args = []) { return add_query_arg(array_merge(['page' => $page], $args), admin_url('admin.php')); }

function da_register_cliente_type() {
    register_post_type('da_cliente', [
        'labels' => ['name' => 'Clientes', 'singular_name' => 'Cliente', 'add_new_item' => 'Cadastrar cliente', 'edit_item' => 'Editar cliente'],
        'public' => false, 'show_ui' => false, 'show_in_rest' => false, 'supports' => ['title'],
        'capability_type' => 'post', 'map_meta_cap' => true,
    ]);
    $fields = [
        '_da_cliente_telefone' => 'string', '_da_cliente_email' => 'string', '_da_cliente_observacoes' => 'string',
        '_da_cliente_cadastrado_em' => 'string', '_da_cliente_ativo' => 'boolean',
    ];
    foreach ($fields as $key => $type) register_post_meta('da_cliente', $key, ['type' => $type, 'single' => true, 'show_in_rest' => false, 'sanitize_callback' => $type === 'boolean' ? 'rest_sanitize_boolean' : ($key === '_da_cliente_observacoes' ? 'sanitize_textarea_field' : 'sanitize_text_field'), 'auth_callback' => static fn() => current_user_can('edit_posts')]);
}
add_action('init', 'da_register_cliente_type');

function da_crm_assets($hook) {
    if (strpos((string) $hook, 'decorart-admin') === false) return;
    wp_register_style('decorart-crm-admin', false, [], '1.0.0'); wp_enqueue_style('decorart-crm-admin');
    wp_add_inline_style('decorart-crm-admin', '.da-form{background:#fff;border:1px solid #e2e8e5;border-radius:14px;padding:22px;max-width:900px}.da-form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.da-field{display:flex;flex-direction:column;gap:6px}.da-field.full{grid-column:1/-1}.da-field label{font-weight:700;color:#33423d}.da-field input,.da-field select,.da-field textarea{border:1px solid #ccd8d3;border-radius:8px;padding:9px;max-width:100%}.da-field textarea{min-height:90px}.da-actions{display:flex;gap:9px;align-items:center;margin-top:20px;flex-wrap:wrap}.da-table{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e2e8e5;border-radius:12px;overflow:hidden}.da-table th,.da-table td{text-align:left;padding:12px;border-bottom:1px solid #edf1ef;vertical-align:top}.da-table th{background:#f3f7f5;color:#42534d}.da-muted{color:#64736e;font-size:13px}.da-toolbar{display:flex;gap:10px;justify-content:space-between;align-items:center;margin:0 0 18px;flex-wrap:wrap}.da-toolbar form{display:flex;gap:7px}.da-toolbar input{min-width:230px}.da-history{margin-top:26px}.da-badge{display:inline-block;border-radius:999px;padding:4px 9px;color:#fff;font-size:12px;font-weight:700}.da-calendar{width:100%;border-collapse:separate;border-spacing:4px;table-layout:fixed}.da-calendar th{padding:8px;color:#52645d}.da-calendar td{height:105px;background:#fff;border:1px solid #e2e8e5;border-radius:8px;vertical-align:top;padding:6px}.da-calendar td.da-today{border:2px solid #247f79}.da-day{font-weight:800;color:#42534d}.da-event-chip{display:block;color:#fff;text-decoration:none;border-radius:5px;padding:4px 5px;margin-top:4px;font-size:11px;line-height:1.15;overflow:hidden}.da-week{display:grid;grid-template-columns:repeat(7,minmax(0,1fr));gap:8px}.da-week-day{background:#fff;border:1px solid #e2e8e5;border-radius:10px;min-height:250px;padding:9px}.da-week-day h3{margin:0 0 8px;font-size:14px}.da-empty-day{color:#87958f;font-size:12px}.da-section-title{margin:26px 0 12px}@media(max-width:700px){.da-form-grid{grid-template-columns:1fr}.da-field.full{grid-column:auto}.da-table{font-size:13px;display:block;overflow-x:auto}.da-calendar{font-size:11px}.da-calendar td{height:78px;padding:3px}.da-event-chip{font-size:10px;padding:3px}.da-week{display:block}.da-week-day{margin-bottom:8px;min-height:80px}.da-toolbar input{min-width:0;width:100%}.da-toolbar form{width:100%}}');
}
add_action('admin_enqueue_scripts', 'da_crm_assets');

function da_save_cliente_action() {
    if (!da_crm_can()) wp_die('Sem permissão.'); check_admin_referer('da_save_cliente', 'da_cliente_nonce');
    $id = isset($_POST['cliente_id']) ? absint($_POST['cliente_id']) : 0; $nome = sanitize_text_field(wp_unslash($_POST['nome'] ?? ''));
    if ($nome === '') wp_die('Informe o nome do cliente.');
    $args = ['post_title' => $nome, 'post_type' => 'da_cliente', 'post_status' => 'publish']; if ($id) $args['ID'] = $id;
    $id = $id ? wp_update_post($args, true) : wp_insert_post($args, true); if (is_wp_error($id)) wp_die($id->get_error_message());
    update_post_meta($id, '_da_cliente_telefone', sanitize_text_field(wp_unslash($_POST['telefone'] ?? '')));
    update_post_meta($id, '_da_cliente_email', sanitize_email(wp_unslash($_POST['email'] ?? '')));
    update_post_meta($id, '_da_cliente_observacoes', sanitize_textarea_field(wp_unslash($_POST['observacoes'] ?? '')));
    update_post_meta($id, '_da_cliente_ativo', isset($_POST['ativo']) ? 1 : 0);
    if (!$id || !get_post_meta($id, '_da_cliente_cadastrado_em', true)) update_post_meta($id, '_da_cliente_cadastrado_em', current_time('mysql'));
    wp_safe_redirect(da_admin_url('decorart-admin-clientes', ['saved' => 1])); exit;
}
add_action('admin_post_da_save_cliente', 'da_save_cliente_action');

function da_save_evento_action() {
    if (!da_crm_can()) wp_die('Sem permissão.'); check_admin_referer('da_save_evento', 'da_evento_nonce');
    $id = isset($_POST['evento_id']) ? absint($_POST['evento_id']) : 0; $cliente_id = absint($_POST['cliente_id'] ?? 0); $data = da_sanitize_date(wp_unslash($_POST['data'] ?? ''));
    if (!$cliente_id || get_post_type($cliente_id) !== 'da_cliente') wp_die('Selecione um cliente.'); if (!$data) wp_die('Informe a data do evento.');
    $nome_cliente = get_the_title($cliente_id); $titulo = sanitize_text_field(wp_unslash($_POST['titulo'] ?? '')) ?: ($nome_cliente . ' — ' . date_i18n('d/m/Y', strtotime($data)));
    $args = ['post_title' => $titulo, 'post_type' => 'da_evento', 'post_status' => 'publish']; if ($id) $args['ID'] = $id;
    $id = $id ? wp_update_post($args, true) : wp_insert_post($args, true); if (is_wp_error($id)) wp_die($id->get_error_message());
    $values = ['_da_cliente_id' => $cliente_id, '_da_evento_data' => $data, '_da_evento_hora' => da_sanitize_time(wp_unslash($_POST['hora'] ?? '')), '_da_montagem_data' => da_sanitize_date(wp_unslash($_POST['montagem_data'] ?? '')), '_da_montagem_hora' => da_sanitize_time(wp_unslash($_POST['montagem_hora'] ?? '')), '_da_evento_local' => sanitize_text_field(wp_unslash($_POST['local'] ?? '')), '_da_evento_tema' => sanitize_text_field(wp_unslash($_POST['tema'] ?? '')), '_da_evento_observacoes' => sanitize_textarea_field(wp_unslash($_POST['observacoes'] ?? '')), '_da_evento_status' => da_sanitize_event_status(wp_unslash($_POST['status'] ?? 'pre_reserva'))];
    foreach ($values as $key => $value) update_post_meta($id, $key, $value);
    wp_safe_redirect(da_admin_url('decorart-admin-agenda', ['saved' => 1])); exit;
}
add_action('admin_post_da_save_evento', 'da_save_evento_action');

function da_cliente_events($cliente_id) { return get_posts(['post_type' => 'da_evento', 'post_status' => 'publish', 'numberposts' => -1, 'meta_key' => '_da_evento_data', 'orderby' => 'meta_value', 'order' => 'ASC', 'meta_query' => [['key' => '_da_cliente_id', 'value' => absint($cliente_id), 'compare' => '=']]]); }
function da_eventos_between($start, $end) { return get_posts(['post_type' => 'da_evento', 'post_status' => 'publish', 'numberposts' => -1, 'meta_key' => '_da_evento_data', 'orderby' => 'meta_value', 'order' => 'ASC', 'meta_query' => [['key' => '_da_evento_data', 'value' => [$start, $end], 'compare' => 'BETWEEN', 'type' => 'DATE']]]); }
function da_render_clientes_page() {
    if (!da_crm_can()) wp_die('Sem permissão.'); $action = sanitize_key($_GET['action'] ?? 'list'); $id = absint($_GET['id'] ?? 0);
    if ($action === 'edit') { da_render_cliente_form($id); return; }
    $search = sanitize_text_field(wp_unslash($_GET['s'] ?? '')); $q = new WP_Query(['post_type' => 'da_cliente', 'post_status' => 'publish', 'posts_per_page' => 50, 's' => $search, 'orderby' => 'title', 'order' => 'ASC']);
    ?><div class="wrap da-admin-wrap"><div class="da-toolbar"><div><h1>Clientes</h1><p class="da-muted">Mini-CRM simples da DecorArt.</p></div><a class="button button-primary" href="<?php echo esc_url(da_admin_url('decorart-admin-clientes', ['action' => 'edit'])); ?>">+ Novo cliente</a></div><?php if (isset($_GET['saved'])) echo '<div class="notice notice-success is-dismissible"><p>Cliente salvo.</p></div>'; ?><div class="da-toolbar"><form method="get"><input type="hidden" name="page" value="decorart-admin-clientes"><input name="s" value="<?php echo esc_attr($search); ?>" placeholder="Buscar por nome"><button class="button">Buscar</button></form></div><table class="da-table"><thead><tr><th>Nome</th><th>WhatsApp</th><th>E-mail</th><th>Status</th><th>Ações</th></tr></thead><tbody><?php if (!$q->have_posts()) : ?><tr><td colspan="5">Nenhum cliente cadastrado.</td></tr><?php else : while ($q->have_posts()) : $q->the_post(); $cid = get_the_ID(); $active = (bool) get_post_meta($cid, '_da_cliente_ativo', true); ?><tr><td><strong><?php the_title(); ?></strong></td><td><?php echo esc_html(get_post_meta($cid, '_da_cliente_telefone', true)); ?></td><td><?php echo esc_html(get_post_meta($cid, '_da_cliente_email', true)); ?></td><td><span class="da-badge" style="background:<?php echo $active ? '#2f9e6e' : '#7b8794'; ?>"><?php echo $active ? 'Ativo' : 'Inativo'; ?></span></td><td><a href="<?php echo esc_url(da_admin_url('decorart-admin-clientes', ['action' => 'edit', 'id' => $cid])); ?>">Abrir cliente</a></td></tr><?php endwhile; wp_reset_postdata(); endif; ?></tbody></table></div><?php
}
function da_render_cliente_form($id = 0) {
    $p = $id ? get_post($id) : null; if ($id && (!$p || $p->post_type !== 'da_cliente')) wp_die('Cliente não encontrado.'); $nome = $p ? $p->post_title : ''; $events = $id ? da_cliente_events($id) : [];
    ?><div class="wrap da-admin-wrap"><div class="da-toolbar"><h1><?php echo $id ? 'Editar cliente' : 'Novo cliente'; ?></h1><a class="button" href="<?php echo esc_url(da_admin_url('decorart-admin-clientes')); ?>">Voltar para clientes</a></div><form class="da-form" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="da_save_cliente"><input type="hidden" name="cliente_id" value="<?php echo esc_attr($id); ?>"><?php wp_nonce_field('da_save_cliente', 'da_cliente_nonce'); ?><div class="da-form-grid"><div class="da-field full"><label for="da-nome">Nome</label><input id="da-nome" name="nome" required value="<?php echo esc_attr($nome); ?>"></div><div class="da-field"><label for="da-telefone">Telefone / WhatsApp</label><input id="da-telefone" name="telefone" value="<?php echo esc_attr($id ? get_post_meta($id, '_da_cliente_telefone', true) : ''); ?>"></div><div class="da-field"><label for="da-email">E-mail (opcional)</label><input id="da-email" type="email" name="email" value="<?php echo esc_attr($id ? get_post_meta($id, '_da_cliente_email', true) : ''); ?>"></div><div class="da-field full"><label for="da-observacoes">Observações</label><textarea id="da-observacoes" name="observacoes"><?php echo esc_textarea($id ? get_post_meta($id, '_da_cliente_observacoes', true) : ''); ?></textarea></div><div class="da-field"><label><input type="checkbox" name="ativo" value="1" <?php checked(!$id || get_post_meta($id, '_da_cliente_ativo', true)); ?>> Cliente ativo</label></div></div><div class="da-actions"><button class="button button-primary">Salvar cliente</button><?php if ($id) : ?><a class="button" href="<?php echo esc_url(da_admin_url('decorart-admin-agenda', ['action' => 'edit', 'cliente_id' => $id])); ?>">Novo evento para este cliente</a><?php endif; ?></div></form><?php if ($id) : ?><section class="da-history"><h2>Histórico de eventos</h2><table class="da-table"><thead><tr><th>Evento</th><th>Data</th><th>Status</th></tr></thead><tbody><?php if (!$events) : ?><tr><td colspan="3">Nenhum evento cadastrado.</td></tr><?php else : foreach ($events as $e) {$st = get_post_meta($e->ID, '_da_evento_status', true) ?: 'pre_reserva'; echo '<tr><td><a href="'.esc_url(da_admin_url('decorart-admin-agenda', ['action'=>'edit','id'=>$e->ID])).'">'.esc_html($e->post_title).'</a></td><td>'.esc_html(get_post_meta($e->ID,'_da_evento_data',true)).'</td><td><span class="da-badge" style="background:'.esc_attr(da_event_status_color($st)).'">'.esc_html(da_event_status_label($st)).'</span></td></tr>';} endif; ?></tbody></table></section><?php endif; ?></div><?php
}
function da_render_agenda_page() {
    if (!da_crm_can()) wp_die('Sem permissão.'); if (($_GET['action'] ?? '') === 'edit') { da_render_evento_form(absint($_GET['id'] ?? 0), absint($_GET['cliente_id'] ?? 0), sanitize_text_field(wp_unslash($_GET['date'] ?? ''))); return; }
    $view = sanitize_key($_GET['view'] ?? 'month'); $year = max(2020, min(2100, absint($_GET['ano'] ?? current_time('Y')))); $month = max(1, min(12, absint($_GET['mes'] ?? current_time('m'))));
    ?><div class="wrap da-admin-wrap"><div class="da-toolbar"><div><h1>Agenda / Planner</h1><p class="da-muted">Acompanhe eventos e datas de montagem.</p></div><a class="button button-primary" href="<?php echo esc_url(da_admin_url('decorart-admin-agenda', ['action'=>'edit'])); ?>">+ Novo evento</a></div><?php if (isset($_GET['saved'])) echo '<div class="notice notice-success is-dismissible"><p>Evento salvo.</p></div>'; ?><div class="da-toolbar"><div><a class="button <?php echo $view==='month'?'button-primary':''; ?>" href="<?php echo esc_url(da_admin_url('decorart-admin-agenda',['view'=>'month','ano'=>$year,'mes'=>$month])); ?>">Mês</a> <a class="button <?php echo $view==='week'?'button-primary':''; ?>" href="<?php echo esc_url(da_admin_url('decorart-admin-agenda',['view'=>'week','ano'=>$year,'mes'=>$month])); ?>">Semana</a></div><div><a class="button" href="<?php echo esc_url(da_admin_url('decorart-admin-agenda',['view'=>$view,'ano'=>$month===1?$year-1:$year,'mes'=>$month===1?12:$month-1])); ?>">‹ Anterior</a> <a class="button" href="<?php echo esc_url(da_admin_url('decorart-admin-agenda',['view'=>$view,'ano'=>current_time('Y'),'mes'=>current_time('m')])); ?>">Hoje</a> <a class="button" href="<?php echo esc_url(da_admin_url('decorart-admin-agenda',['view'=>$view,'ano'=>$month===12?$year+1:$year,'mes'=>$month===12?1:$month+1])); ?>">Próximo ›</a></div></div><?php
    if ($view === 'week') da_render_week_view($year, $month); else da_render_month_view($year, $month); echo '</div>';
}
function da_render_month_view($year, $month) {
    $start = sprintf('%04d-%02d-01', $year, $month); $end = date('Y-m-t', strtotime($start)); $events = da_eventos_between($start, $end); $days = [];
    foreach ($events as $e) $days[(int)date('j', strtotime(get_post_meta($e->ID,'_da_evento_data',true)))][] = $e;
    echo '<h2>'.esc_html(date_i18n('F Y', strtotime($start))).'</h2><table class="da-calendar"><thead><tr><th>Seg</th><th>Ter</th><th>Qua</th><th>Qui</th><th>Sex</th><th>Sáb</th><th>Dom</th></tr></thead><tbody><tr>';
    $offset = (int)date('N', strtotime($start))-1; for($i=0;$i<$offset;$i++) echo '<td></td>'; $today=current_time('Y-m-d');
    for($d=1;$d<=date('t',strtotime($start));$d++){ $date=sprintf('%04d-%02d-%02d',$year,$month,$d); $cls=$date===$today?' class="da-today"':''; echo '<td'.$cls.'><a class="da-day" href="'.esc_url(da_admin_url('decorart-admin-agenda',['action'=>'edit','date'=>$date])).'">'.$d.'</a>'; foreach(($days[$d]??[]) as $e){$st=get_post_meta($e->ID,'_da_evento_status',true)?:'pre_reserva'; echo '<a class="da-event-chip" style="background:'.esc_attr(da_event_status_color($st)).'" href="'.esc_url(da_admin_url('decorart-admin-agenda',['action'=>'edit','id'=>$e->ID])).'">'.esc_html($e->post_title).'</a>';} echo '</td>'; if(($offset+$d)%7===0 && $d<date('t',strtotime($start))) echo '</tr><tr>'; } echo '</tr></tbody></table><p class="da-muted">Clique em um dia vazio para criar um evento com a data preenchida.</p>';
}
function da_render_week_view($year, $month) {
    $base = strtotime(sprintf('%04d-%02d-15', $year, $month)); $monday = strtotime('monday this week', $base); $start=date('Y-m-d',$monday); $end=date('Y-m-d',strtotime('+6 days',$monday)); $events=da_eventos_between($start,$end); $days=[]; foreach($events as $e)$days[get_post_meta($e->ID,'_da_evento_data',true)][]=$e;
    echo '<h2>Semana de '.esc_html(date_i18n('d/m/Y',$monday)).'</h2><div class="da-week">'; for($i=0;$i<7;$i++){ $ts=strtotime('+'.$i.' days',$monday); $date=date('Y-m-d',$ts); echo '<section class="da-week-day"><h3>'.esc_html(date_i18n('D d/m',$ts)).'</h3>'; if(empty($days[$date])) echo '<a class="da-empty-day" href="'.esc_url(da_admin_url('decorart-admin-agenda',['action'=>'edit','date'=>$date])).'">+ Criar evento</a>'; foreach(($days[$date]??[]) as $e){$st=get_post_meta($e->ID,'_da_evento_status',true)?:'pre_reserva'; echo '<a class="da-event-chip" style="background:'.esc_attr(da_event_status_color($st)).'" href="'.esc_url(da_admin_url('decorart-admin-agenda',['action'=>'edit','id'=>$e->ID])).'">'.esc_html($e->post_title).'</a>';} echo '</section>'; } echo '</div>';
}
function da_render_evento_form($id=0,$cliente_id=0,$date='') {
    $p=$id?get_post($id):null; if($id&&(!$p||$p->post_type!=='da_evento'))wp_die('Evento não encontrado.'); $client_saved=$p?(int)get_post_meta($id,'_da_cliente_id',true):$cliente_id; $date_saved=$p?get_post_meta($id,'_da_evento_data',true):$date; $clients=get_posts(['post_type'=>'da_cliente','post_status'=>'publish','numberposts'=>-1,'orderby'=>'title','order'=>'ASC']); $v=function($key)use($id){return $id?get_post_meta($id,$key,true):'';};
    ?><div class="wrap da-admin-wrap"><div class="da-toolbar"><h1><?php echo $id?'Editar evento':'Novo evento'; ?></h1><a class="button" href="<?php echo esc_url(da_admin_url('decorart-admin-agenda')); ?>">Voltar para agenda</a></div><form class="da-form" method="post" action="<?php echo esc_url(admin_url('admin-post.php')); ?>"><input type="hidden" name="action" value="da_save_evento"><input type="hidden" name="evento_id" value="<?php echo esc_attr($id); ?>"><?php wp_nonce_field('da_save_evento','da_evento_nonce'); ?><div class="da-form-grid"><div class="da-field full"><label for="da-evento-titulo">Nome do evento</label><input id="da-evento-titulo" name="titulo" value="<?php echo esc_attr($p?$p->post_title:''); ?>" placeholder="Ex.: Aniversário da Maria"></div><div class="da-field"><label for="da-cliente-select">Cliente</label><select id="da-cliente-select" name="cliente_id" required><option value="">Selecione o cliente</option><?php foreach($clients as $c) echo '<option value="'.esc_attr($c->ID).'" '.selected($client_saved,$c->ID,false).'>'.esc_html($c->post_title).'</option>'; ?></select><?php if(!$clients) echo '<span class="da-muted">Cadastre um cliente antes de criar o evento.</span>'; ?></div><div class="da-field"><label for="da-status-select">Status do evento</label><select id="da-status-select" name="status"><?php foreach(da_event_statuses() as $key=>$label) echo '<option value="'.esc_attr($key).'" '.selected($v('_da_evento_status')?:'pre_reserva',$key,false).'>'.esc_html($label).'</option>'; ?></select></div><div class="da-field"><label>Data do evento</label><input type="date" name="data" required value="<?php echo esc_attr($date_saved); ?>"></div><div class="da-field"><label>Horário do evento</label><input type="time" name="hora" value="<?php echo esc_attr($v('_da_evento_hora')); ?>"></div><div class="da-field"><label>Data de montagem</label><input type="date" name="montagem_data" value="<?php echo esc_attr($v('_da_montagem_data')); ?>"></div><div class="da-field"><label>Horário de montagem</label><input type="time" name="montagem_hora" value="<?php echo esc_attr($v('_da_montagem_hora')); ?>"></div><div class="da-field"><label>Local / endereço</label><input name="local" value="<?php echo esc_attr($v('_da_evento_local')); ?>"></div><div class="da-field"><label>Tema</label><input name="tema" value="<?php echo esc_attr($v('_da_evento_tema')); ?>"></div><div class="da-field full"><label>Observações</label><textarea name="observacoes"><?php echo esc_textarea($v('_da_evento_observacoes')); ?></textarea></div></div><div class="da-actions"><button class="button button-primary">Salvar evento</button><a class="button" href="<?php echo esc_url(da_admin_url('decorart-admin-clientes')); ?>">Ir para clientes</a></div></form></div><?php
}
