<?php
/** DecorArt Core — painel administrativo integrado ao WordPress. */
if (!defined('ABSPATH')) { exit; }

function da_admin_modules() { return [
    'dashboard' => ['Dashboard', 'dashicons-dashboard', 'Visão geral da operação.'],
    'agenda' => ['Agenda / Planner', 'dashicons-calendar-alt', 'Datas, eventos e rotina.'],
    'clientes' => ['Clientes / Mini-CRM', 'dashicons-groups', 'Cadastro e histórico de clientes.'],
    'orcamentos' => ['Orçamentos', 'dashicons-media-spreadsheet', 'Propostas e acompanhamento comercial.'],
    'financeiro' => ['Financeiro', 'dashicons-chart-line', 'Receitas, despesas e fluxo.'],
    'custos' => ['Calculadora de custos', 'dashicons-calculator', 'Base para composição de custos.'],
    'acervo' => ['Acervo / Estoque', 'dashicons-archive', 'Móveis, disponibilidade e acervo.'],
]; }
function da_register_admin_pages() {
    $callbacks = ['clientes' => 'da_render_clientes_page', 'agenda' => 'da_render_agenda_page'];
    add_menu_page('Painel DecorArt', 'Painel DecorArt', 'access_decorart_system', 'decorart-admin', 'da_render_admin_page', 'dashicons-art', 3);
    foreach (da_admin_modules() as $slug => $module) add_submenu_page('decorart-admin', $module[0], $module[0], 'access_decorart_system', 'decorart-admin-' . $slug, $callbacks[$slug] ?? 'da_render_admin_page');
}
add_action('admin_menu', 'da_register_admin_pages');
function da_admin_assets($hook) {
    if (strpos((string) $hook, 'decorart-admin') === false) return;
    wp_register_style('decorart-admin-base', false, [], '1.1.0'); wp_enqueue_style('decorart-admin-base');
    wp_add_inline_style('decorart-admin-base', '.da-admin-wrap{max-width:1180px;margin:24px 20px 40px}.da-admin-hero{background:linear-gradient(135deg,#145d5a,#247f79);color:#fff;border-radius:18px;padding:28px 32px;margin-bottom:22px;box-shadow:0 12px 30px rgba(20,93,90,.18)}.da-admin-hero h1{color:#fff;margin:0 0 8px;font-size:28px}.da-admin-hero p{margin:0;color:rgba(255,255,255,.82);font-size:15px}.da-admin-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px}.da-admin-card{background:#fff;border:1px solid #e2e8e5;border-radius:15px;padding:22px;min-height:145px;box-shadow:0 4px 14px rgba(20,50,45,.05);transition:transform .15s,box-shadow .15s}.da-admin-card:hover{transform:translateY(-2px);box-shadow:0 10px 24px rgba(20,50,45,.1)}.da-admin-card h2{font-size:17px;margin:13px 0 7px}.da-admin-card p{color:#64736e;margin:0 0 15px}.da-admin-icon{color:#247f79;font-size:26px}.da-admin-button{display:inline-block;background:#e6f1ef;color:#145d5a;text-decoration:none;border-radius:8px;padding:7px 11px;font-weight:600}.da-admin-status{display:inline-flex;gap:7px;align-items:center;color:#52705f;font-size:13px}.da-admin-status:before{content:"";width:8px;height:8px;border-radius:50%;background:#7ca43a}.da-admin-kpis{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;margin:0 0 22px}.da-admin-kpi{background:#fff;border:1px solid #e2e8e5;border-radius:12px;padding:16px}.da-admin-kpi strong{display:block;font-size:25px;color:#145d5a}.da-admin-kpi span{font-size:12px;color:#64736e}.da-dashboard-list{background:#fff;border:1px solid #e2e8e5;border-radius:14px;padding:18px;margin-bottom:22px}.da-dashboard-list h2{font-size:18px;margin-top:0}.da-dashboard-list li{padding:9px 0;border-bottom:1px solid #edf1ef}.da-dashboard-list li:last-child{border-bottom:0}@media(max-width:1000px){.da-admin-kpis{grid-template-columns:repeat(3,1fr)}.da-admin-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:560px){.da-admin-wrap{margin:15px 10px}.da-admin-grid,.da-admin-kpis{grid-template-columns:1fr}.da-admin-hero{padding:22px}.da-admin-hero h1{font-size:23px}}');
}
add_action('admin_enqueue_scripts', 'da_admin_assets');
function da_admin_current_slug() { $page = isset($_GET['page']) ? sanitize_key(wp_unslash($_GET['page'])) : 'decorart-admin'; return str_replace('decorart-admin-', '', $page) ?: 'dashboard'; }
function da_render_admin_page() {
    if (!da_can_system()) wp_die('Você não tem permissão para acessar esta área.');
    $modules=da_admin_modules(); $slug=da_admin_current_slug(); if(!isset($modules[$slug]))$slug='dashboard'; $module=$modules[$slug]; $items=wp_count_posts('da_item'); $eventos=wp_count_posts('da_evento'); $clientes=wp_count_posts('da_cliente'); $today=current_time('Y-m-d'); $today_events=function_exists('da_eventos_between')?da_eventos_between($today,$today):[]; $upcoming=function_exists('da_eventos_between')?da_eventos_between($today,date('Y-m-d',strtotime('+30 days',current_time('timestamp')))):[];
    ?><div class="wrap da-admin-wrap"><section class="da-admin-hero"><h1><?php echo esc_html($module[0]); ?></h1><p>Sistema DecorArt · operação de clientes e eventos.</p></section><?php if($slug==='dashboard'): ?><div class="da-admin-kpis"><div class="da-admin-kpi"><strong><?php echo (int)($clientes->publish??0); ?></strong><span>Clientes cadastrados</span></div><div class="da-admin-kpi"><strong><?php echo (int)count($today_events); ?></strong><span>Eventos hoje</span></div><div class="da-admin-kpi"><strong><?php echo (int)count(array_filter($upcoming,function($e){return get_post_meta($e->ID,'_da_evento_status',true)==='pre_reserva';})); ?></strong><span>Pré-reservas</span></div><div class="da-admin-kpi"><strong><?php echo (int)count(array_filter($upcoming,function($e){return get_post_meta($e->ID,'_da_evento_status',true)==='confirmado';})); ?></strong><span>Confirmados próximos</span></div><div class="da-admin-kpi"><strong><?php echo (int)($eventos->publish??0); ?></strong><span>Total de eventos</span></div></div><div class="da-dashboard-list"><h2>Eventos de hoje</h2><?php if(!$today_events): ?><p class="da-muted">Nenhum evento para hoje.</p><?php else: ?><ul><?php foreach($today_events as $e){$st=get_post_meta($e->ID,'_da_evento_status',true)?:'pre_reserva'; echo '<li><a href="'.esc_url(da_admin_url('decorart-admin-agenda',['action'=>'edit','id'=>$e->ID])).'">'.esc_html($e->post_title).'</a> · '.esc_html(da_event_status_label($st)).'</li>';} ?></ul><?php endif; ?></div><div class="da-dashboard-list"><h2>Próximos eventos</h2><?php if(!$upcoming): ?><p class="da-muted">Nenhum evento nos próximos 30 dias.</p><?php else: ?><ul><?php foreach(array_slice($upcoming,0,10) as $e){$st=get_post_meta($e->ID,'_da_evento_status',true)?:'pre_reserva'; echo '<li><a href="'.esc_url(da_admin_url('decorart-admin-agenda',['action'=>'edit','id'=>$e->ID])).'">'.esc_html(get_post_meta($e->ID,'_da_evento_data',true)).' — '.esc_html($e->post_title).'</a> · '.esc_html(da_event_status_label($st)).'</li>';} ?></ul><?php endif; ?></div><?php else: ?><div class="notice notice-info"><p><strong><?php echo esc_html($module[0]); ?>:</strong> estrutura preparada para uma etapa futura.</p></div><?php endif; ?><div class="da-admin-grid"><?php foreach($modules as $key=>$card):if($key===$slug)continue;$url=admin_url('admin.php?page=decorart-admin-'.$key); ?><article class="da-admin-card"><span class="dashicons <?php echo esc_attr($card[1]); ?> da-admin-icon" aria-hidden="true"></span><h2><?php echo esc_html($card[0]); ?></h2><p><?php echo esc_html($card[2]); ?></p><a class="da-admin-button" href="<?php echo esc_url($url); ?>">Abrir módulo</a></article><?php endforeach; ?></div><p class="da-admin-status" style="margin-top:22px">Área protegida pela autenticação e pelas permissões do WordPress.</p></div><?php
}
